### ISSUE TITLE
wait is blocking whole ruby interpreter

### ISSUE THREAD

**Issue by graf0** [djberg96/win32-mutex#1]
Hello!

I'm trying to use Win32::Mutex to signalize child process, when parent dies. Problem is that I have many threads. When I call mx.wait in some thread - whole ruby interprenter hangs, till mutex is released.

Solution to this is quite simple accualy - just change those two lines in win32/ipc.rb from:

    attach_function :WaitForSingleObject, [:handle, :dword], :dword
    attach_function :WaitForMultipleObjects, [:dword, :pointer, :bool, :dword], :dword

to:

    attach_function :WaitForSingleObject, [:handle, :dword], :dword, blocking: true
    attach_function :WaitForMultipleObjects, [:dword, :pointer, :bool, :dword], :dword, blocking: true

Cheers

**Comment by djberg96** [comment]
Ok, updated and pushed win32-ipc. Thanks for the report!
